// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ispindel/BrewSession.tsx": () => import("../components/mockups/ispindel/BrewSession.tsx"),
  "./components/mockups/ispindel/SensorsSettings.tsx": () => import("../components/mockups/ispindel/SensorsSettings.tsx")
};
